# SPDX-License-Identifier: GPL-3.0-or-later

mountOptions:
  default: defaults
  btrfs: defaults,noatime,compress=zstd:1
  vfat: umask=0077

ssdExtraMountOptions:
  ext4: discard=async
  btrfs: discard=async

efiMountOptions: umask=0077
