# SPDX-License-Identifier: GPL-3.0-or-later

method: legacy
packageChoice: kde-plasma
qmlSearch: branding
qmlFilename: packagechooser-desktop

labels:
  step: "Desktop Environment"
  step[tr]: "Masaüstü Ortamı"
