# SPDX-License-Identifier: GPL-3.0-or-later

method: legacy
packageChoice: linux-zen
qmlSearch: branding
qmlFilename: packagechooser-kernel

labels:
  step: "Linux Kernel"
  step[tr]: "Linux Çekirdeği"
