# SPDX-License-Identifier: GPL-3.0-or-later

method: legacy
packageChoice: privacy
qmlSearch: branding
qmlFilename: packagechooser-profile

labels:
  step: "Installation Profile"
  step[tr]: "Kurulum Profili"
