# SPDX-License-Identifier: GPL-3.0-or-later

efiSystemPartition: "/boot"
efiSystemPartitionSize: 512MiB
defaultFileSystemType: "ext4"
availableFileSystemTypes:
  - "ext4"
  - "btrfs"

userSwapChoices:
  - none
  - file
  - small
initialSwapChoice: file
drawNestedPartitions: true

defaultPartitionTableType: gpt
