# SPDX-License-Identifier: GPL-3.0-or-later
#
# Top-level SchweisOS Calamares sequence. Configuration is packaged separately
# from Calamares itself and installed under /etc/calamares.

modules-search: [ local ]
branding: schweisos
prompt-install: false

instances:
  - id: preflight
    module: shellprocess
    config: shellprocess-preflight.conf
  - id: kernel
    module: packagechooser
    config: packagechooser-kernel.conf
  - id: extras
    module: packagechooser
    config: packagechooser-extras.conf
  - id: reconcile
    module: shellprocess
    config: shellprocess-reconcile.conf
  - id: pacman
    module: shellprocess
    config: shellprocess-pacman.conf
  - id: systemd-boot
    module: shellprocess
    config: shellprocess-systemd-boot.conf
  - id: services
    module: shellprocess
    config: shellprocess-services.conf

sequence:
  - show:
      - welcomeq
      - locale
      - keyboard
      - packagechooser@kernel
      - packagechooser@extras
      - partition
      - users
      - summary
  - exec:
      - shellprocess@preflight
      - partition
      - mount
      - unpackfs
      - shellprocess@reconcile
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - hwclock
      - shellprocess@pacman
      - shellprocess@systemd-boot
      - shellprocess@services
      - umount
  - show:
      - finished
