# SPDX-License-Identifier: GPL-3.0-or-later

dontChroot: true
timeout: 1800
verbose: true
script:
  - "/usr/lib/schweisos-calamares/reconcile-target ${ROOT} ${gs[packagechooser_browser]} ${gs[packagechooser_kernel]} ${gs[packagechooser_profile]} ${gs[packagechooser_extras]} ${gs[packagechooser_extras_mode]} ${gs[packagechooser_desktop]}"
