# SPDX-License-Identifier: GPL-3.0-or-later

defaultGroups:
  - wheel
  - video
  - audio
  - storage
  - network
  - power

sudoersGroup: wheel
setRootPassword: false
doAutologin: false
userShell: /usr/bin/bash
